### ISSUE TITLE
Only one champion vote per day 

### ISSUE THREAD

**Issue by kevinbischof** [kimhogeling/burp2gether#10]
It would make sense, that a user can only vote one champion in a day. The user can take this one vote back and give it to someone else. Therefore, a ranking would make sense to get the best burper of all!

**Comment by kimhogeling** [comment]
It should already be like that. It's possible to give multiple 🏆  on a day, but only one for each day. Example scenario: a new user can give one 🏆 for today, one for yesterday, one for the day before and on and on all the way back to the first day.
Did i understand correctly?

**Comment by kevinbischof** [comment]
Ah ok. I didn't check that this is already implemented as I tought. Therefore, I'll close this issue.
