### ISSUE TITLE
Add favourites-system (follow users)

### ISSUE THREAD

**Issue by kimhogeling** [kimhogeling/burp2gether#5]
So langsam werden wir viele und wir möchten nicht unbedingt jeden sehen. Das einfachste, wäre ein "folgen" System.

**Comment by kimhogeling** [comment]
Brauchen wir Follow-Anfragen (wie bei Insta) oder soll jeder jeden einfach folgen können (wie z.B. Twitter). Wenn Anfragen, dann konfigurierbar, ob man das doch für alle offen haben will?

**Comment by kevinbischof** [comment]
Ja burps öffentlich posten können oder nur für Follower bzw Freunde.

**Comment by kimhogeling** [comment]
@kevinbischof  ah ja, ok, ob ein Burp öffentlich ist oder nur für Follower, das sprengt den Rahmen dieses Tickets, aber das Feature wäre auch super! Dazu habe ich ein neues Ticket erstellt: #20
