### ISSUE TITLE
if (false) makes no sense

### ISSUE THREAD

**Issue by nx-kevinbischof** [kimhogeling/burp2gether#9]
https://github.com/kimhogeling/burp2gether/blob/c1f13096d06b104778cafff0e2ea0fb411e72b52/src/App.svelte#LL17C7-L17C13
the condition if (false || ...) will never be true :D

**Comment by kimhogeling** [comment]
This is a stupid bug that slipped in! It was for quicker local testing. Luckily it does no harm. It just doesn't hide some markup when it should..
